SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_VELOCITY = 100
ASTEROID_MAX_VELOCITY = 350
ASTEROID_ROTATION_MAX_OFFSET = 15

PLAYER_RADIUS = 20
PLAYER_VELOCITY = 200
PLAYER_ROTATION_SPEED = 300
